name: api_fake_store
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.5.3

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  chopper: ^8.0.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.13
  chopper_generator: ^8.0.3
  dartz: ^0.10.1
  logger: ^2.5.0
